name: "divein coaching"
description: "big data and behavioral sciences applied to immersive distance education"

url: "http://rpietro.github.io"

pagination: true
paginate: 10

markdown: redcarpet
permalink: pretty
pygments: true